config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'tweets#index'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users do
    resources :tweets, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates :user, uniqueness: {scope: :tweet}
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :likes
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  has_one_attached :profile_picture

  attr_accessor :remove_profile_picture

before_save :check_remove_profile_picture

def check_remove_profile_picture
  profile_picture.purge if remove_profile_picture == '1'
end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:email, :username, :password, :password_confirmation, :current_password, :profile_picture])
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_tweet
    before_action :find_comment, only: [:destroy]

    def create
        @comment = @tweet.comments.new(comment_params)
        @comment.user = current_user

        if @comment.save
            redirect_to @tweet
        else
            redirect_to tweets_path, notice: 'Comment failed to post'
        end
    end

    def destroy
        if @comment.user == current_user
            @comment.destroy
            redirect_to @tweet
        else
            redirect_to @tweet, notice: 'Comment failed to delete'
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end

    def find_tweet
        @tweet = Tweet.find(params[:tweet_id])
    end

    def find_comment
        @comment = @tweet.comments.find(params[:id])
    end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        like = tweet.likes.new(user: current_user)
        if like.save
            redirect_to tweets_path, notice: 'Tweet liked!'
        else
            redirect_to tweets_path, alert: 'You have already liked this tweet'
        end
    end

    def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)

        like.destroy
        redirect_to tweets_path, notice: 'Tweet unliked'
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    def index
        @tweets = Tweet.includes(:user).all.order(created_at: :desc)
    end

    def show
        @tweet = Tweet.find(params[:id])
    end

    def create
        @tweet = current_user.tweets.build(tweet_params)
            if @tweet.save

                redirect_to tweets_path
                flash[:notice] = "Thanks for posting!"
            else
                render '_new'
            end
    end

    def edit
        @tweet = Tweet.find(params[:id]) 
    end

    def update 
        @tweet = current_user.tweets.find(params[:id])
        if @tweet.update(tweet_params)
            redirect_to @tweet, notice: 'Tweet has been successfully edited.'
        else
            render :edit
        end
    end

    def destroy
        @tweet = current_user.tweets.find(params[:id])
        @tweet.destroy
        redirect_to tweets_path, notice: 'Tweet was deleted'
    end


    private
    def tweet_params
        params.require(:tweet).permit(:content)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end

    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class='navbar'>
      <div class='navbar-left'>
        <a href="<%= tweets_path %>">Tweeter</a>
      </div>
      
      <div class='navbar-right'>
        <% if user_signed_in? && current_user.profile_picture.attached? %>
          <%= image_tag current_user.profile_picture.variant(resize: "30x30"), class: 'rounded-avatar' %>
        <% end %>
    
        <% if user_signed_in? %>
          <%= link_to 'View Account', edit_user_registration_path, class: 'btn btn-info' %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </nav>
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p> 
      <%= yield %>
  </body>
</html>

app/views/tweets/_new.html.erb
<%= form_with model: @tweet, url: tweets_path, method: :post do |t| %>
    <%= t.hidden_field "tweet[user_id]"%>
    <%= t.text_area "tweet[content]", class: 'new-tweet-text-area', placeholder: "What's on your mind?" %>
    <%= t.submit 'Tweet', class: 'submit-tweet-button' %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="single-tweet-container">
    <div class="tweet-avatar">
        <%= image_tag tweet.user.profile_picture.variant(resize: "50x50"), class: 'rounded-avatar' if tweet.user.profile_picture.attached? %>
    </div>
    <div class="single-tweet-content">
        <p class="single-tweet-text"><%= tweet.content %></p>
        <h4 class="tweet-username"><%= link_to tweet.user.username, user_path(tweet.user) %></h4>

        <div class="single-tweet-actions">
            <% if tweet.user == current_user %>
                <%= link_to 'Edit', edit_tweet_path(tweet), class: 'btn single-tweet-btn-primary' %>
                <%= link_to 'Delete', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn single-tweet-btn-danger' %>
            <% end %>

            <% if current_user.liked_tweets.include?(tweet) %>
                <%= button_to 'Unlike', tweet_like_path(tweet, tweet.likes.find_by(user: current_user)), method: :delete, class: 'single-tweet-action unlike' %>
            <% else %>
                <%= button_to 'Like', tweet_likes_path(tweet), method: :post, class: 'single-tweet-action like' %>
            <% end %>

            <span class="single-tweet-likes"><%= tweet.likes.count %> likes</span>
            <%= link_to 'Comment', tweet_path(tweet), class: 'single-tweet-action-comment' %>
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="tweet-edit-container">
  <h2 class='edit-tweet-title'>Edit Tweet</h2>

  <%= form_with(model: @tweet, local: true) do |form| %>
    <% if @tweet.errors.any? %>
      <div class="tweet-error-explanation">
        <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
        <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="tweet-field">
      <%= form.label :content, class: 'tweet-label' %><br />
      <%= form.text_area :content, class: 'tweet-textarea' %>
    </div>

    <div class="tweet-actions">
      <%= form.submit "Update Tweet", class: 'btn tweet-btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Back', tweets_path, class: 'tweet-back-link' %>
</div>

app/views/tweets/index.html.erb
<div class='center container'>
    <div class='new-tweet-container'>
        <%= render 'new' %>
    </div>

    <div class="tweets-container">
        <% @tweets.each do |t| %>
            <div class="tweet">
                <div class="tweet-avatar">
                    <%= image_tag t.user.profile_picture.variant(resize: "50x50"), class: 'rounded-avatar' if t.user.profile_picture.attached? %>
                </div>
                <div class="tweet-content">
                    <p class="tweet-text"><%= t.content %></p>
                    <h4 class="tweet-username"><%= link_to t.user.username, user_path(t.user) %></h4>

                    <div class="tweet-actions">
                        <% if t.user == current_user %>
                            <%= link_to 'Edit', edit_tweet_path(t), class: 'btn btn-edit-delete action-item' %>
                            <%= button_to 'Delete', t, method: :delete, class: 'btn btn-edit-delete action-item' %>
                        <% end %>

                        <% if current_user.liked_tweets.include?(t) %>
                            <%= button_to 'Unlike', tweet_like_path(t, t.likes.find_by(user: current_user)), method: :delete, class: 'btn-tweet-action unlike action-item' %>
                        <% else %>
                            <%= button_to 'Like', tweet_likes_path(t), method: :post, class: 'btn-tweet-action like action-item' %>
                        <% end %>

                        <span class="tweet-likes action-item"><%= t.likes.count %> likes</span>
                        <%= link_to 'Comment', tweet_path(t), class: 'btn-tweet-action-comment action-item' %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Test Text</h1>
        </div>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="tweet-detail-container">

  <h2 class="tweet-owner"><%= @tweet.user.username %>'s Tweet</h2>

  <div class="tweet-content-container">
    <p class="tweet-content">
      <%= @tweet.content %>
    </p>
    <div class="tweet-actions">
      <% if @tweet.user == current_user %>
        <%= link_to 'Edit', edit_tweet_path(@tweet), class: 'tweet-action-edit' %> 
        <%= link_to 'Delete', tweet_path(@tweet), method: :delete, data: { confirm: 'Are you sure?' }, class: 'tweet-action-delete' %>
      <% end %>
    </div>
  </div>

  <h3 class="comments-header">Comments</h3>

  <div class="comments-container">
    <% @tweet.comments.each do |comment| %>
      <div class="comment">
        <strong class="comment-username"><%= comment.user.username %></strong>
        <%= image_tag comment.user.profile_picture.variant(resize: "30x30"), class: 'rounded-avatar' if comment.user.profile_picture.attached? %>
        <p class="comment-content"><%= comment.content %></p>
        <div class="comment-actions">
          <% if comment.user == current_user %>
            <%= button_to 'Delete', tweet_comment_path(@tweet, comment), method: :delete, class: 'comment-action-delete' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="comment-form-container">
    <%= form_for [@tweet, Comment.new] do |f| %>
      <%= f.text_area :content, placeholder: 'Add a comment...', class: 'comment-textarea' %>
      <%= f.submit 'Post Comment', class: 'comment-submit' %>
    <% end %>
  </div>

  <div class="back-link-container">
    <%= link_to 'Back', tweets_path, class: 'back-link' %>
  </div>

</div>

app/views/users/index.html.erb
<h1>Registered Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1 class='single-user-tweets-title'><%= @user.username %>'s Tweets</h1>

<%= render @user.tweets.order(created_at: :desc) %>

<div class='user-tweets-back-link'>
    <%= link_to 'Back', tweets_path %>
</div>